### ISSUE TITLE
Missing strings are replaced with other language strings if missing

### ISSUE THREAD

**Issue by waldemarfm** [Nobox/Lazy-Strings#2]
Example: If app is in english and some strings only exist in spanish, LazyStrings uses the spanish copy as content instead of showing the string ID to note the string copy as missing.

This isn't a bug but it should show the ID to indicate that the string is missing.

Screenshot: Boleto Dorado in english mode is showing spanish strings that exist in spanish tab instead of original IDs:

![screen shot 2014-12-15 at 17 45 53](https://cloud.githubusercontent.com/assets/1105953/5445486/411c3a76-8482-11e4-8deb-da349cbefb7d.png)

**Comment by waldemarmedina** [comment]
Recent projects have proved that this bug is no longer happening.
