### ISSUE TITLE
Put all Lazy strings under the same namespace, like "lazy".

### ISSUE THREAD

**Issue by waldemarfm** [Nobox/Lazy-Strings#3]
All lazy strings should be under "lazy" namespace. For example:

``` php
{{ trans('lazy.string.id') }}
```

This would be helpful to avoid conflicts between app's own language strings and those coming from Lazy.

**Comment by antoniwan** [comment]
I suggest writing an extra function that does the same.

IE: Instead of calling `{{ trans('lazy.string.id') }}`, call something like `{{ ctrans('string.id') }}` to avoid writing `lazy` in every string occurrence.

**Comment by waldemarmedina** [comment]
Pichaera

**Comment by cyberkiko** [comment]
:8ball:

**Comment by jonathantorres** [comment]
I'll have this for next week. Pinky promise. :cake:
