### ISSUE TITLE
Replicate nesting behavior on generated php files

### ISSUE THREAD

**Issue by waldemarfm** [Nobox/Lazy-Strings#7]
An advantage of doing Laravel lang files by hand is that you can nest the arrays indefinitely. This is useful if we want to loop through all copy lines inside another, like in the MLB trivia questions.

PHP files generated from LazyStrings remove this nesting. It would be a great feature to keep this nesting intact.

Example:

An id 'home.hero.headline' with copy 'Lorem ipsum...' would be:

``` php
...
'home' => [
  'hero' => [
    'headline' => 'Lorem Ipsum...',
  ],
],
...
```

instead of the single dimension of:

``` php
'home.hero.headline' => 'Lorem Ipsum...',
```

**Comment by jonathantorres** [comment]
Implemented, details are here: https://github.com/Nobox/Lazy-Strings/releases/tag/v3.1.0
